### ISSUE TITLE
Doesn't fire callbacks on macOs

### ISSUE THREAD

**Issue by petrbrzek** [miguelmota/big-red-button#1]
Device is connected, but callbacks (buttonPressed, ...) won't fire. I tried this library, and it works fine https://github.com/bettse/BigRedButton. Any clued where could be a problem? I tried to put console.log to `this.hid.read` in your code but nothing happened.

**Comment by miguelmota** [comment]
@petrbrzek I've updated `node-hid` and it's working now.

Thanks for reporting!
